### ISSUE TITLE
Missing file in "'models/instructions_processed_LP“

### ISSUE THREAD

**Issue by Cyuanwen** [hitachi-rd-cv/prompter#1]
Thank you for your great works! I have met an error when run the main.py, as follows:
```
No such file or directory: 'models/instructions_processed_LP/instruction2_params_test_unseen_noappended.p'
```
When I copy those .p file from [FILM project](https://github.com/soyeonm/FILM/tree/public/models/instructions_processed_LP) and run the code, I get KeyError, which mean those missing files are not from FILM project. Can you share those file? Thank you very much!

**Comment by yinoue0426** [comment]
Sorry about that, it is completely my bad.

I just pushed the files, so please check
