### ISSUE TITLE
Time Consumption

### ISSUE THREAD

**Issue by felixfjg** [hitachi-rd-cv/prompter#3]
I'm curious how long the author took to run on the test split, as there are too many episodes in the test set (1500+ for unseen and seen split).

**Comment by yinoue0426** [comment]
Unfortunately, I don't have a recorded time, and I don't remember how long it took to run on test sets, since I only ran the model on test sets a few number of times.

I do remember that it took about 8~10 hours on validation unseen, using 3 PC's in parallel, each of which ran 2 processes in parallel.

Just a rough estimate, but if you have 1 PC which runs 2 processes in parallel, since there are 821 runs in validation unseen and test seen and unseen both have about 1530 runs each, it comes out at around 10 hrs * (1530 * 2) / 821 = 37 hrs.

But of course, if you have _N_ PCs, it'll take 37 / _N_ hours.

**Comment by felixfjg** [comment]
Thank you for your excellent work and detailed responses. Perhaps it's an issue on my end. I'm testing on an RTX 3090 with 2 processes, and each episode takes approximately 10 minutes, thus it comes out at around 10 mins * (1530 * 2) / 60 = 510 hrs. It could be related to the RTX 3090's computational power, or it might also be related to forwarding X11 to my local Windows host.

**Comment by felixfjg** [comment]
Thank you for your excellent work and detailed responses. Perhaps it's an issue on my end. I'm testing on 4 RTX 3090 GPU with 2 processes, and each episode takes approximately 10 minutes, thus it comes out at around 10 mins * (1530 * 2) / 60 = 510 hrs. It could be related to the RTX 3090's computational power, or it might also be related to forwarding X11 to my local Windows host.

**Comment by yinoue0426** [comment]
Yeah that doesn't sound right. In the above mentioned settings, I was using RTX2080Ti.

Does "4 RTX 3090 GPU with 2 processes" mean 1 PC with 4 GPU's on it? I will note that this project, having multiple PCs is more effective than having one PC with a strong computational power, though that doesn't really improve your situation all that much.

Also, if you are running main.py with `--debug_env` or `--save_pictures` flag, you should remove them, as they are for debugging purposes and slows down the inference process.

**Comment by felixfjg** [comment]
Thank you very much!

> Does "4 RTX 3090 GPU with 2 processes" mean 1 PC with 4 GPU's on it?

Yeah, that's right. I have a machine (linux server) with 4 RTX3090, and I run 2 processes on it. And I follow your suggestion to remove `--debug_env` and `--save_pictures` flags.

- Before removal: Each episode needs 10 minute averagely.
- After removal: Each epsiodes needs 6 minute averagely.
  
It become faster, however, is still too slow. I need to use X11-forwarding on windows using MobaXterm, then the graphical interface will be displayed on the Windows PC (as shown below); otherwise I cannot run successfully. Do you need x11-forwarding? I think its the main cause of my slow runtime. Is there a corresponding solution to this?
![image](https://github.com/hitachi-rd-cv/prompter-alfred/assets/93566509/b0ae044d-ff9a-4a1c-873c-d60919733f34)

**Comment by yinoue0426** [comment]
> I need to use X11-forwarding on windows using MobaXterm, then the graphical interface will be displayed on the Windows PC ... I think its the main cause of my slow runtime.

I agree. Sending GUI information over the network sounds like a time-consuming task.



> Is there a corresponding solution to this?

You are probably looking for information [here](https://github.com/hitachi-rd-cv/prompter-alfred#running-with-headless-machines).

Assuming that you are running experiments on Ubuntu machine, you can set up a virtual display which can be used to trick the ALFRED/THOR environment to think that there is an actual display attached to the machine. This way, you don't need to send the GUI information over the network, probably reducing the experimentation time.

**Comment by felixfjg** [comment]
> You are probably looking for information [here](https://github.com/hitachi-rd-cv/prompter-alfred#running-with-headless-machines).

I tried it when I run this project at first time. However, it failed at that time due to a lack of root permissions. Now I have contacted the server administrator and successfully set up the virtual display. Thanks for your patient reply.
